name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    if: contains(github.event.head_commit.message, '#ci') || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies
        run: nix develop --command yarn install

      - name: Build & zip
        run: |
          nix develop --command yarn zip:chrome &
          nix develop --command yarn zip:firefox &
          wait
          rm -f .output/*-sources.zip

      - name: Upload Chrome zip
        uses: actions/upload-artifact@v4
        with:
          name: chrome-zip
          path: .output/chrome-mv3/
          include-hidden-files: true

      - name: Upload Firefox zip
        uses: actions/upload-artifact@v4
        with:
          name: firefox-zip
          path: .output/firefox-mv2/
          include-hidden-files: true

      - name: Create release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: .output/*.zip
